<a href="https://colab.research.google.com/github/2303A52440/GenerativeAi_2025/blob/main/generate_Ai_assigment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Actual values and predicted values
Y_actual = np.array([20, 30, 40, 50, 60])
Y_pred = np.array([20.5, 30.3, 40.2, 50.6, 60.7])

# Calculate error metrics from scratch
MAE = np.mean(np.abs(Y_actual - Y_pred))
MSE = np.mean((Y_actual - Y_pred) ** 2)
RMSE = np.sqrt(MSE)

print("From Scratch:")
print(f"MAE: {MAE}")
print(f"MSE: {MSE}")
print(f"RMSE: {RMSE}")

# Calculate error metrics using scikit-learn
MAE_lib = mean_absolute_error(Y_actual, Y_pred)
MSE_lib = mean_squared_error(Y_actual, Y_pred)
RMSE_lib = np.sqrt(MSE_lib)

print("\nUsing Libraries:")
print(f"MAE (library): {MAE_lib}")
print(f"MSE (library): {MSE_lib}")
print(f"RMSE (library): {RMSE_lib}")


From Scratch:
MAE: 0.4600000000000016
MSE: 0.24600000000000147
RMSE: 0.49598387070549127

Using Libraries:
MAE (library): 0.4600000000000016
MSE (library): 0.24600000000000147
RMSE (library): 0.49598387070549127


In [1]:
import numpy as np # make sure to import numpy in this cell too!
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

Y_actual = np.array([0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2])
Y_pred = np.array([0, 0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 1, 0, 2, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 0, 2, 1, 2, 2, 2])

accuracy = accuracy_score(Y_actual, Y_pred)
print(f"Accuracy: {accuracy:.2f}")

precision = precision_score(Y_actual, Y_pred, average=None)
for i in range(len(precision)):
    print(f"Class {i} - Precision: {precision[i]:.2f}")

recall = recall_score(Y_actual, Y_pred, average=None)
for i in range(len(recall)):
    print(f"Class {i} - Recall: {recall[i]:.2f}")

f1 = f1_score(Y_actual, Y_pred, average=None)
for i in range(len(f1)):
    print(f"Class {i} - F1-Score: {f1[i]:.2f}")

conf_matrix = confusion_matrix(Y_actual, Y_pred)
print("\nConfusion Matrix:")
print(conf_matrix)

print("\nDetailed Classification Report:")
print(classification_report(Y_actual, Y_pred))

Accuracy: 0.73
Class 0 - Precision: 0.78
Class 1 - Precision: 0.71
Class 2 - Precision: 0.71
Class 0 - Recall: 0.64
Class 1 - Recall: 0.62
Class 2 - Recall: 0.91
Class 0 - F1-Score: 0.70
Class 1 - F1-Score: 0.67
Class 2 - F1-Score: 0.80

Confusion Matrix:
[[ 7  2  2]
 [ 1  5  2]
 [ 1  0 10]]

Detailed Classification Report:
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        11
           1       0.71      0.62      0.67         8
           2       0.71      0.91      0.80        11

    accuracy                           0.73        30
   macro avg       0.74      0.72      0.72        30
weighted avg       0.74      0.73      0.73        30

